export const SET_TAMIL_ALBUMS = 'SET_TAMIL_ALBUMS';
export const SET_ARTIST_LIST = 'SET_ARTIST_LIST';
export const SET_PAGENAME = 'SET_PAGENAME';
export const SET_PREVIOUS_PAGENAME = 'SET_PREVIOUS_PAGENAME';
export const GET_LASTPLAYED_SONG = 'GET_LASTPLAYED_SONG';
export const SET_TRACK_LIST = 'SET_TRACK_LIST';
export const SET_HEADER_SONG_NAME = 'SET_HEADER_SONG_NAME';